In [2]:
import scipy.io
import numpy as np
import matplotlib.pyplot as plt
import os
import fast

In [3]:
# load data
data = "mnist"

file_name = 'mnist_all.mat'
relative_path =   '/../data'

# get save path 
save_path = os.getcwd() + relative_path # https://stackoverflow.com/questions/39125532/file-does-not-exist-in-jupyter-notebook
full_path = os.path.join(save_path, file_name)
assert  os.path.exists(full_path), f'Path {relative_path}/{file_name} does not exist'

# read scipy.io
mat = scipy.io.loadmat(full_path)

In [4]:

# ideally get this from data 
n_class_units=10 
n_pixel=784  # per img
n_examples=60000

# preprocessing 
inputs=np.zeros((0,n_pixel)) # empty array in correct shape for later (unneccessary??)
for i in range(n_class_units): # iterate over mat dictionary 
    inputs=np.concatenate((inputs, mat['train'+str(i)]), axis=0) # get entries of dict 
inputs=inputs/255.0 # normalize 
print(inputs) #shape (60000, 784) 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# select algorithm 
algorithm = "fast"

fast.training(inputs, n_hidden=100)

TypeError: training() takes 2 positional arguments but 3 were given